import LoginModal from "@/components/modals/LoginModal";
import "./globals.css";
import Layout from "@/components/Layout";
import RegisterModal from "@/components/modals/RegisterModal";
import { Toaster } from "react-hot-toast";
import Provider from "@/components/Provider";
import EditModal from "@/components/modals/EditModal";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Toaster />
          <RegisterModal />
          <LoginModal />
          <EditModal />
          <Layout>{children}</Layout>
        </Provider>
      </body>
    </html>
  );
}
